### ISSUE TITLE
integrate fixes/improvements from github.com/sideshowdave7/gomq

### ISSUE THREAD

**Issue by sbinet** [zeromq/gomq#61]
hi there,

For neugram.io (and gophernotes) we need to interact with [Jupyter](https://jupyter.org).
This is done via ZeroMQ.
But installing the Go bindings to the C++ library is a pain so going the pure-Go route would be neat.

In order to do this, we need multipart support (among other things.)
Fortunately, this has been implemented by @sideshowdave7:
https://github.com/zeromq/gomq/compare/master...sideshowdave7:master

any reason why this couldn't be integrated back into `zeromq/gomq` proper ?

**Comment by sbinet** [comment]
Ping @all ?

**Comment by sideshowdave7** [comment]
I'd be happy to get the code PR-ready.  I believe just a little testing is necessary for that, from testing i did some time ago the only issue I noticed was memory consumption growing over time.

**Comment by sbinet** [comment]
SGTM :)

**Comment by sbinet** [comment]
hi,
anything I could do to help you with ?

**Comment by SpencerPark** [comment]
[gophernotes](https://github.com/gopherdata/gophernotes) is currently dependent on c bindings for zmq and we would like to move away for that. 

@sideshowdave7 These additions cover almost all of what we need in order to write a Jupyter kernel in pure Go. Is there anything we can help with to get things moving upstream? :)

**Comment by luna-duclos** [comment]
I'd be happy to merge if a PR comes in

**Comment by sbinet** [comment]
gentle ping @sideshowdave7  :)
